consul:
  image: progrium/consul
  container_name: consul
  ports:
    - "8500:8500"
  command: "-server -bootstrap -ui-dir /ui"
  restart: always

restclient:
  image: restclient
  ports:
    - "8081:8080"
    - "8989:8989"
    - "4000:4000"
  environment:
    - "SPRING_APPLICATION_NAME=restclient"
    - "SPRING_PROFILES_ACTIVE=mode1"
    - "SPRING_CLOUD_CONSUL_HOST=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_PORT=8081"
    - "INITIAL_DELAY=1" #local 1 ms
    - "IS_INITIAL_DELAY_RANDOM=true" #remote true
    - "JMX_REMOTE_HOST=10.199.50.114"
  volumes_from: #until depends_on will be introduced
    - consul


restsender:
  image: restsender
  ports:
    - "8082:8080"
    - "8981:8981"
    - "4001:4001"
  environment:
    - "SPRING_APPLICATION_NAME=restsender"
    - "SPRING_PROFILES_ACTIVE=mode1"
    - "SPRING_CLOUD_CONSUL_HOST=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_PORT=8082"
    - "INITIAL_DELAY=1" #remote 200 ms
    - "IS_INITIAL_DELAY_RANDOM=true" #remote true
    - "JMX_REMOTE_HOST=10.199.50.114"
  volumes_from: #until depends_on will be introduced
    - consul

thriftclient:
  image: thriftclient
  ports:
    - "8083:8080"
    - "8990:8990"
    - "4002:4002"
  environment:
    - "SPRING_APPLICATION_NAME=thriftclient"
    - "SPRING_PROFILES_ACTIVE=mode1"
    - "SPRING_CLOUD_CONSUL_HOST=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_PORT=8083"
    - "INITIAL_DELAY=1" #local 1 ms
    - "IS_INITIAL_DELAY_RANDOM=true" #remote true
    - "JMX_REMOTE_HOST=10.199.50.114"
  volumes_from: #until depends_on will be introduced
    - consul

thriftsender:
  image: thriftsender
  ports:
    - "8084:8080"
    - "8991:8991"
    - "4003:4003"
  environment:
    - "SPRING_APPLICATION_NAME=thriftsender"
    - "SPRING_PROFILES_ACTIVE=mode1"
    - "SPRING_CLOUD_CONSUL_HOST=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=10.199.50.114"
    - "SPRING_CLOUD_CONSUL_DISCOVERY_PORT=8084"
    - "INITIAL_DELAY=1" #remote 200 ms
    - "IS_INITIAL_DELAY_RANDOM=true" #remote true
    - "JMX_REMOTE_HOST=10.199.50.114"
  volumes_from: #until depends_on will be introduced
    - consul
