consul:
  image: progrium/consul
  container_name: consul
  ports:
    - "8500:8500"
  command: "-server -bootstrap -ui-dir /ui"
  restart: always

registrator:
  image: gliderlabs/registrator
  container_name: registrator
  net: "host"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  command: "-ip 192.168.1.33 consul://192.168.1.33:8500"
  restart: always

#restclient:
#  image: restclient
#  ports:
#    - "8080"
#    - "9110"
#  environment:
#    - "SPRING_CLOUD_CONSUL_HOST=192.168.1.33"
#    - "JAVA_OPTS=-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=192.168.1.33 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.rmi.port=9110"

resthandler:
  image: resthandler
  ports:
    - "8080"
  environment:
    - "SPRING_CLOUD_CONSUL_HOST=192.168.1.33"

thrifthandler:
  image: thrifthandler
  ports:
    - "8080"
  environment:
    - "SPRING_CLOUD_CONSUL_HOST=192.168.1.33"